version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5004:5004'
      - '8000:8000'
    command: tail -f /dev/null
    environment:
      APP_NAME: auth-plus-monetization
      PORT: 5004
      PYTHON_ENV: development
      DATABASE_URL: postgresql+psycopg2://root:db_password@database:5432/monetization
      REDIS_URL: cache
      KAFKA_URL: localhost:9092
    volumes:
      - .:/app
    restart: always
    networks:
      - monetization-net

  messaging:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python -m src.presentation.messaging
    environment:
      APP_NAME: auth-plus-monetization
      PORT: 5004
      PYTHON_ENV: development
      DATABASE_URL: postgresql+psycopg2://root:db_password@database:5432/monetization
      REDIS_URL: cache
      KAFKA_URL: localhost:9092
    volumes:
      - .:/app
    restart: always
    networks:
      - monetization-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run huey_consumer.py src.presentation.worker.huey -k greenlet -w 4
    environment:
      APP_NAME: auth-plus-monetization
      PYTHON_ENV: development
      DATABASE_URL: postgresql+psycopg2://root:db_password@database:5432/monetization
      REDIS_URL: cache
      KAFKA_URL: localhost:9092
    volumes:
      - .:/app
    restart: always
    networks:
      - monetization-net
  
  database:
    container_name: postgres
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: root
      POSTGRES_DB: monetization
    ports:
      - '5432:5432'
    volumes:
      - v-database:/var/lib/postgres
    networks:
      - monetization-net
  
  cache:
    container_name: redis
    image: redis:7.0.5
    hostname: redis
    restart: always
    volumes:
      - v-cache:/data
    ports:
      - '6379:6379'
    networks:
      - monetization-net

networks:
  monetization-net:
    driver: bridge

volumes:
  v-database:
  v-cache:
