services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5004:5004'
      - '8000:8000'
    command: tail -f /dev/null
    environment:
      APP_NAME: auth-plus-monetization
      PORT: 5004
      PYTHON_ENV: development
      DATABASE_URL: postgresql+psycopg2://root:db_password@database:5432/monetization
      KAFKA_URL: localhost:9092
    volumes:
      - .:/app
    restart: always
    networks:
      - monetization-net

  job:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python3 -m src.presentation.worker
    environment:
      APP_NAME: auth-plus-monetization
      PYTHON_ENV: development
      DATABASE_URL: postgresql+psycopg2://root:db_password@database:5432/monetization
      KAFKA_URL: localhost:9092
    volumes:
      - .:/app
    restart: always
    networks:
      - monetization-net
  
  database:
    container_name: postgres
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: root
      POSTGRES_DB: monetization
    ports:
      - '5432:5432'
    volumes:
      - v-database:/var/lib/postgres
    networks:
      - monetization-net

networks:
  monetization-net:
    driver: bridge

volumes:
  v-database:
  v-cache:
