version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency
    ports:
      - '5005:5005'
    command: tail -f /dev/null
    environment:
      APP_NAME: auth-plus-monetization
      PORT: 5005
      PYTHON_ENV: development
    volumes:
      - .:/app
    restart: always
    networks:
      - monetization-net

networks:
  monetization-net:
    driver: bridge