version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency
    ports:
      - '5004:5004'
    command: tail -f /dev/null
    environment:
      APP_NAME: auth-plus-monetization
      PORT: 5004
      PYTHON_ENV: development
    volumes:
      - .:/app
    restart: always
    networks:
      - monetization-net

  database:
    container_name: postgres
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: root
      POSTGRES_DB: monetization
    ports:
      - '5432:5432'
    volumes:
      - v-database:/var/lib/postgres
    networks:
      - monetization-net

networks:
  monetization-net:
    driver: bridge

volumes:
  v-database:
